// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Tests.SGP.Features.GROT._01_Bloco01._01_11_SequeciaCenica
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("01.11 - Sequência Cênica", new string[] {
            "kill_Driver"}, Description="Narrativa:\r\n\tEu como adminstrador do sistema\r\n\tQuero criar uma sequencia cenica\r\n" +
        "\tPara determinar a ordem de gravação das cenas do produto", SourceFile="Features\\GROT\\01 - Bloco 01\\01.11 - SequeciaCenica\\01.11 - SequeciaCenica.feature" +
        "", SourceLine=6)]
    public partial class _01_11_SequenciaCenicaFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "01.11 - SequeciaCenica.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "01.11 - Sequência Cênica", "Narrativa:\r\n\tEu como adminstrador do sistema\r\n\tQuero criar uma sequencia cenica\r\n" +
                    "\tPara determinar a ordem de gravação das cenas do produto", ProgrammingLanguage.CSharp, new string[] {
                        "kill_Driver"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 14
#line 15
 testRunner.Given("que eu navegue para a Tela de Login do SGP", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 16
 testRunner.And("efetuar o login no sistema do SGP", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 18
 testRunner.And("que eu navegue para a tela de sequecia cenica", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("01 - Listagem de Sequências Cênicas", new string[] {
                "chrome",
                "excluir_SequenciaCenica",
                "logout"}, SourceLine=20)]
        public virtual void _01_ListagemDeSequenciasCenicas()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("01 - Listagem de Sequências Cênicas", new string[] {
                        "chrome",
                        "excluir_SequenciaCenica",
                        "logout"});
#line 21
this.ScenarioSetup(scenarioInfo);
#line 14
this.FeatureBackground();
#line 22
 testRunner.Given("que eu tenho uma sequencia cenica criada", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 23
 testRunner.When("eu faco busca pela sequencia cenica somente por cenas nao gravadas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 24
 testRunner.Then("eu visualizo a sequencia cenica criada com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("02 - Filtrar Sequência Cênica", new string[] {
                "chrome",
                "excluir_SequenciaCenica",
                "logout"}, SourceLine=26)]
        public virtual void _02_FiltrarSequenciaCenica()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("02 - Filtrar Sequência Cênica", new string[] {
                        "chrome",
                        "excluir_SequenciaCenica",
                        "logout"});
#line 27
this.ScenarioSetup(scenarioInfo);
#line 14
this.FeatureBackground();
#line 28
 testRunner.Given("que eu tenho uma sequencia cenica criada", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 29
 testRunner.When("eu faco busca pela sequencia cenica", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 30
 testRunner.Then("eu visualizo a sequencia cenica criada com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("03 - Alteração Sequência Cênica", new string[] {
                "chrome",
                "excluir_SequenciaCenica",
                "logout"}, SourceLine=32)]
        public virtual void _03_AlteracaoSequenciaCenica()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("03 - Alteração Sequência Cênica", new string[] {
                        "chrome",
                        "excluir_SequenciaCenica",
                        "logout"});
#line 33
this.ScenarioSetup(scenarioInfo);
#line 14
this.FeatureBackground();
#line 34
 testRunner.Given("que eu tenho uma sequencia cenica criada", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 35
 testRunner.When("eu faco uma alteracao na sequencia cenica criada", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 36
 testRunner.Then("eu visualizo a altercao feita na sequencia cenica com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04 - Exclusão de Sequência Cênica", new string[] {
                "chrome",
                "logout"}, SourceLine=38)]
        public virtual void _04_ExclusaoDeSequenciaCenica()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("04 - Exclusão de Sequência Cênica", new string[] {
                        "chrome",
                        "logout"});
#line 39
this.ScenarioSetup(scenarioInfo);
#line 14
this.FeatureBackground();
#line 40
 testRunner.Given("que eu tenho uma sequencia cenica criada", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 41
 testRunner.When("eu excluo a sequencia cenica", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 42
 testRunner.Then("eu nao visualizo mas a sequencia cenica com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("05 - Criação de Nova Sequência Cênica", new string[] {
                "chrome",
                "excluir_SequenciaCenica",
                "logout"}, SourceLine=44)]
        public virtual void _05_CriacaoDeNovaSequenciaCenica()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("05 - Criação de Nova Sequência Cênica", new string[] {
                        "chrome",
                        "excluir_SequenciaCenica",
                        "logout"});
#line 45
this.ScenarioSetup(scenarioInfo);
#line 14
this.FeatureBackground();
#line 46
 testRunner.When("eu criar uma sequencia cenica", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 47
 testRunner.Then("eu visualizo a sequencia cenica criada com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("06 - Alteração de Sequência Cênica", new string[] {
                "chrome",
                "excluir_SequenciaCenica",
                "logout"}, SourceLine=49)]
        public virtual void _06_AlteracaoDeSequenciaCenica()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("06 - Alteração de Sequência Cênica", new string[] {
                        "chrome",
                        "excluir_SequenciaCenica",
                        "logout"});
#line 50
this.ScenarioSetup(scenarioInfo);
#line 14
this.FeatureBackground();
#line 51
 testRunner.Given("que eu tenho uma sequencia cenica criada", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 52
 testRunner.When("eu altero a ordem da sequemcia", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 53
 testRunner.Then("eu visualizo a sequencia cenica criada na ordem desejada com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("07 - Listagem de Cena", new string[] {
                "chrome",
                "logout"}, SourceLine=55)]
        public virtual void _07_ListagemDeCena()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("07 - Listagem de Cena", new string[] {
                        "chrome",
                        "logout"});
#line 56
this.ScenarioSetup(scenarioInfo);
#line 14
this.FeatureBackground();
#line 57
 testRunner.When("eu clico no botao de nova sequencia cenica", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 58
 testRunner.Then("eu visualizo as cenas existentes para o produto com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("08 - Definição de Sequência", new string[] {
                "chrome",
                "excluir_SequenciaCenica",
                "logout"}, SourceLine=60)]
        public virtual void _08_DefinicaoDeSequencia()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("08 - Definição de Sequência", new string[] {
                        "chrome",
                        "excluir_SequenciaCenica",
                        "logout"});
#line 61
this.ScenarioSetup(scenarioInfo);
#line 14
this.FeatureBackground();
#line 62
 testRunner.When("eu criar uma sequencia cenica na ordem desejada", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 63
 testRunner.Then("eu visualizo a sequencia cenica criada com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("09 - Resumo das cenas", new string[] {
                "chrome",
                "logout"}, SourceLine=65)]
        public virtual void _09_ResumoDasCenas()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("09 - Resumo das cenas", new string[] {
                        "chrome",
                        "logout"});
#line 66
this.ScenarioSetup(scenarioInfo);
#line 14
this.FeatureBackground();
#line 67
 testRunner.When("eu clico num cena", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 68
 testRunner.Then("eu visualizo os detalhes da cena com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("10 - Filtro das cenas", new string[] {
                "chrome",
                "logout"}, SourceLine=70)]
        public virtual void _10_FiltroDasCenas()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("10 - Filtro das cenas", new string[] {
                        "chrome",
                        "logout"});
#line 71
this.ScenarioSetup(scenarioInfo);
#line 14
this.FeatureBackground();
#line 72
 testRunner.Given("que eu clico no botao de nova sequencia cenica", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 73
 testRunner.When("eu clico no botao de filtrar cenas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 74
 testRunner.Then("eu visualizo as opcoes de filtro de cenas disponiveis com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("11 - Formas de Visualização", new string[] {
                "chrome",
                "logout"}, SourceLine=76)]
        public virtual void _11_FormasDeVisualizacao()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("11 - Formas de Visualização", new string[] {
                        "chrome",
                        "logout"});
#line 77
this.ScenarioSetup(scenarioInfo);
#line 14
this.FeatureBackground();
#line 78
 testRunner.When("eu clico no botao de nova sequencia cenica", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 79
 testRunner.Then("eu visualizo as cenas por cenario e capitulos com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
