// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Tests.SGP.Features.GROT._01_Bloco01._01_03_DecupagemBasica
{
    using TechTalk.SpecFlow;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("01.03 - Decupagem basica GROT", new string[] {
            "kill_Driver"}, Description = "Narrativa:\r\n\tEu como adminstrador do sistema\r\n\tQuero criar um novo Capítulo no SG" +
        "P\r\n\tPara ter controle dos Capítulos e Cenas que serão roterizados\r\n\t\r\nFora de es" +
        "copo:\r\n\tTestes negativos", SourceFile = "Features\\GROT\\01 - Bloco 01\\01.03 - DecupagemBasica\\01.03 - DecupagemBasicaGROT.f" +
        "eature", SourceLine = 5)]
    public partial class _01_03_DecupagemBasicaGROTFeature
    {

        private TechTalk.SpecFlow.ITestRunner testRunner;

#line 1 "01.03 - DecupagemBasicaGROT.feature"
#line hidden

        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "01.03 - Decupagem basica GROT", "Narrativa:\r\n\tEu como adminstrador do sistema\r\n\tQuero criar um novo Capítulo no SG" +
                    "P\r\n\tPara ter controle dos Capítulos e Cenas que serão roterizados\r\n\t\r\nFora de es" +
                    "copo:\r\n\tTestes negativos", ProgrammingLanguage.CSharp, new string[] {
                        "kill_Driver"});
            testRunner.OnFeatureStart(featureInfo);
        }

        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }

        public virtual void TestInitialize()
        {
        }

        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }

        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }

        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }

        public virtual void FeatureBackground()
        {
#line 16
#line 17
            testRunner.Given("que eu navegue para a Tela de Login do SGP", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 18
            testRunner.And("efetuar o login no sistema do SGP", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 19
            testRunner.And("que eu navegue para a Tela Home com a programacao selecionada", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 20
            testRunner.And("que eu criar um novo capitulo", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
        }

        [TechTalk.SpecRun.ScenarioAttribute("01 - Novos campos na tela de Decupagem - Carregar as informações padrões", new string[] {
                "chrome",
                "excluir_NovoCapitulo",
                "logout"}, SourceLine = 22)]
        public virtual void _01_NovosCamposNaTelaDeDecupagem_CarregarAsInformacoesPadroes()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("01 - Novos campos na tela de Decupagem - Carregar as informações padrões", new string[] {
                        "chrome",
                        "excluir_NovoCapitulo",
                        "logout"});
#line 23
            this.ScenarioSetup(scenarioInfo);
#line 16
            this.FeatureBackground();
#line 24
            testRunner.Given("que eu navegue para a Tela de Decupagem Basica", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 25
            testRunner.Then("eu visualizo os novos campos de decupagem basica com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }

        [TechTalk.SpecRun.ScenarioAttribute("02 - Alteração no Cadastro de Decupagem", new string[] {
                "chrome",
                "excluir_NovoCapitulo",
                "logout"}, SourceLine = 27)]
        public virtual void _02_AlteracaoNoCadastroDeDecupagem()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("02 - Alteração no Cadastro de Decupagem", new string[] {
                        "chrome",
                        "excluir_NovoCapitulo",
                        "logout"});
#line 28
            this.ScenarioSetup(scenarioInfo);
#line 16
            this.FeatureBackground();
#line 29
            testRunner.Given("que eu navegue para a Tela de Decupagem Basica", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 30
            testRunner.When("eu faco uma decupagem basica preenchendo os novos campos GROT", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 31
            testRunner.Then("eu visualizo os novos campos de decupagem basica com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }

        [TechTalk.SpecRun.ScenarioAttribute("03 - Criação de novo Local de Gravação - Criação de local de gravação", new string[] {
                "chrome",
                "excluir_NovoCapitulo",
                "excluir_NovoCenario",
                "excluir_LocalGravacao",
                "excluir_Regiao",
                "logout"}, SourceLine = 33)]
        public virtual void _03_CriacaoDeNovoLocalDeGravacao_CriacaoDeLocalDeGravacao()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("03 - Criação de novo Local de Gravação - Criação de local de gravação", new string[] {
                        "chrome",
                        "excluir_NovoCapitulo",
                        "excluir_NovoCenario",
                        "excluir_LocalGravacao",
                        "excluir_Regiao",
                        "logout"});
#line 34
            this.ScenarioSetup(scenarioInfo);
#line 16
            this.FeatureBackground();
#line 35
            testRunner.Given("que eu navegue para a Tela de Decupagem Basica", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 36
            testRunner.When("eu crio um novo local durante a decupagem basica", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 37
            testRunner.Then("eu visualizo a Cena criada com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }

        [TechTalk.SpecRun.ScenarioAttribute("04 - Validação da criação dos campos novos para usuário com perfil de rollout gra" +
            "dativo", new string[] {
                "chrome",
                "excluir_NovoCapitulo",
                "logout"}, SourceLine = 39)]
        public virtual void _04_ValidacaoDaCriacaoDosCamposNovosParaUsuarioComPerfilDeRolloutGradativo()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("04 - Validação da criação dos campos novos para usuário com perfil de rollout gra" +
                    "dativo", new string[] {
                        "chrome",
                        "excluir_NovoCapitulo",
                        "logout"});
#line 40
            this.ScenarioSetup(scenarioInfo);
#line 16
            this.FeatureBackground();
#line 41
            testRunner.Given("que eu navegue para a Tela de Decupagem Basica", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 42
            testRunner.When("eu faco uma decupagem basica com perfil GROT", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 43
            testRunner.Then("eu visualizo a Cena criada com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }

        [TechTalk.SpecRun.ScenarioAttribute("05 - Validação dos novos campos", new string[] {
                "chrome",
                "excluir_NovoCapitulo",
                "logout"}, SourceLine = 45)]
        public virtual void _05_ValidacaoDosNovosCampos()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("05 - Validação dos novos campos", new string[] {
                        "chrome",
                        "excluir_NovoCapitulo",
                        "logout"});
#line 46
            this.ScenarioSetup(scenarioInfo);
#line 16
            this.FeatureBackground();
#line 47
            testRunner.Given("que eu navegue para a Tela de Decupagem Basica", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 48
            testRunner.When("eu faco uma decupagem basica preenchendo o campo duracao com caracteres invalidos" +
                               "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 49
            testRunner.Then("eu visualizo a Cena criada com sucesso com o campo duracao exibindo o ultimo cara" +
                               "cter valido", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }

        [TechTalk.SpecRun.ScenarioAttribute("06 - Alteração de parâmetros default", new string[] {
                "chrome",
                "excluir_NovoCapitulo",
                "alterar_ParametroProducao",
                "logout"}, SourceLine = 51)]
        public virtual void _06_AlteracaoDeParametrosDefault()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("06 - Alteração de parâmetros default", new string[] {
                        "chrome",
                        "excluir_NovoCapitulo",
                        "alterar_ParametroProducao",
                        "logout"});
#line 52
            this.ScenarioSetup(scenarioInfo);
#line 16
            this.FeatureBackground();
#line 53
            testRunner.Given("que eu navegue para a Tela de Decupagem Basica", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 54
            testRunner.And("visualizo os novos campos de decupagem basica", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 55
            testRunner.When("eu acesso a tela de parametros", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 56
            testRunner.And("altero os valores padroes desses campos", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 57
            testRunner.Then("eu visualizo os valores atualizados na tela de decupagem basica", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }

        [TechTalk.SpecRun.ScenarioAttribute("07 - Criação de novo local de gravação", new string[] {
                "chrome",
                "excluir_NovoCapitulo",
                "excluir_NovoCenario",
                "excluir_LocalGravacao",
                "excluir_Regiao",
                "logout"}, SourceLine = 59)]
        public virtual void _07_CriacaoDeNovoLocalDeGravacao()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("07 - Criação de novo local de gravação", new string[] {
                        "chrome",
                        "excluir_NovoCapitulo",
                        "excluir_NovoCenario",
                        "excluir_LocalGravacao",
                        "excluir_Regiao",
                        "logout"});
#line 60
            this.ScenarioSetup(scenarioInfo);
#line 16
            this.FeatureBackground();
#line 61
            testRunner.Given("que eu navegue para a Tela de Decupagem Basica", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 62
            testRunner.When("eu crio um novo local durante a decupagem basica", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 63
            testRunner.Then("eu visualizo a Cena criada com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }

        [TechTalk.SpecRun.ScenarioAttribute("08 - Decupagem com alteração dos campos \"default\" na tela", new string[] {
                "chrome",
                "excluir_NovoCapitulo",
                "logout"}, SourceLine = 65)]
        public virtual void _08_DecupagemComAlteracaoDosCamposDefaultNaTela()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("08 - Decupagem com alteração dos campos \"default\" na tela", new string[] {
                        "chrome",
                        "excluir_NovoCapitulo",
                        "logout"});
#line 66
            this.ScenarioSetup(scenarioInfo);
#line 16
            this.FeatureBackground();
#line 67
            testRunner.Given("que eu tenha uma cena decupada", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 68
            testRunner.When("eu realizo uma alteracao na decupagem basica", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 69
            testRunner.And("eu faco busca por cena em consulta de log", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 70
            testRunner.Then("eu visualizo a alteracao feita no log com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }

        [TechTalk.SpecRun.ScenarioAttribute("09 - Decupagem com preenchimento dos campos Local e Local de Gravação", new string[] {
                "chrome",
                "excluir_NovoCapitulo",
                "excluir_NovoCenario",
                "excluir_LocalGravacao",
                "excluir_Regiao",
                "logout"}, SourceLine = 72)]
        public virtual void _09_DecupagemComPreenchimentoDosCamposLocalELocalDeGravacao()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("09 - Decupagem com preenchimento dos campos Local e Local de Gravação", new string[] {
                        "chrome",
                        "excluir_NovoCapitulo",
                        "excluir_NovoCenario",
                        "excluir_LocalGravacao",
                        "excluir_Regiao",
                        "logout"});
#line 73
            this.ScenarioSetup(scenarioInfo);
#line 16
            this.FeatureBackground();
#line 74
            testRunner.Given("que eu navegue para a Tela de Decupagem Basica", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 75
            testRunner.When("eu crio um novo local durante a decupagem basica", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 76
            testRunner.Then("eu visualizo a Cena criada com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }

        [TechTalk.SpecRun.ScenarioAttribute("10 - Decupagem alterando os novos campos", new string[] {
                "chrome",
                "excluir_NovoCapitulo",
                "logout"}, SourceLine = 78)]
        public virtual void _10_DecupagemAlterandoOsNovosCampos()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("10 - Decupagem alterando os novos campos", new string[] {
                        "chrome",
                        "excluir_NovoCapitulo",
                        "logout"});
#line 79
            this.ScenarioSetup(scenarioInfo);
#line 16
            this.FeatureBackground();
#line 80
            testRunner.Given("que eu tenha uma cena decupada", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 81
            testRunner.When("eu realizo uma alteracao na decupagem basica", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 82
            testRunner.And("eu faco busca por cena em consulta de log", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 83
            testRunner.Then("eu visualizo a alteracao feita no log com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }

        [TechTalk.SpecRun.ScenarioAttribute("11 - Criação de decupagem para o período \"Dia\"", new string[] {
                "chrome",
                "excluir_NovoCapitulo",
                "logout"}, SourceLine = 85)]
        public virtual void _11_CriacaoDeDecupagemParaOPeriodoDia()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("11 - Criação de decupagem para o período \"Dia\"", new string[] {
                        "chrome",
                        "excluir_NovoCapitulo",
                        "logout"});
#line 86
            this.ScenarioSetup(scenarioInfo);
#line 16
            this.FeatureBackground();
#line 87
            testRunner.Given("que eu navegue para a Tela de Decupagem Basica", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 88
            testRunner.When("eu faco uma decupagem basica para o periodo Dia", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 89
            testRunner.Then("eu visualizo a Cena criada com periodo dia com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }

        [TechTalk.SpecRun.ScenarioAttribute("12 - Criação de decupagem para o período \"Tarde\"", new string[] {
                "chrome",
                "excluir_NovoCapitulo",
                "logout"}, SourceLine = 91)]
        public virtual void _12_CriacaoDeDecupagemParaOPeriodoTarde()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("12 - Criação de decupagem para o período \"Tarde\"", new string[] {
                        "chrome",
                        "excluir_NovoCapitulo",
                        "logout"});
#line 92
            this.ScenarioSetup(scenarioInfo);
#line 16
            this.FeatureBackground();
#line 93
            testRunner.Given("que eu navegue para a Tela de Decupagem Basica", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 94
            testRunner.When("eu faco uma decupagem basica para o periodo Tarde", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 95
            testRunner.Then("eu visualizo a Cena criada com periodo tarde com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }

        [TechTalk.SpecRun.ScenarioAttribute("13 - Criação de decupagem para o período \"Noite\"", new string[] {
                "chrome",
                "excluir_NovoCapitulo",
                "logout"}, SourceLine = 97)]
        public virtual void _13_CriacaoDeDecupagemParaOPeriodoNoite()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("13 - Criação de decupagem para o período \"Noite\"", new string[] {
                        "chrome",
                        "excluir_NovoCapitulo",
                        "logout"});
#line 98
            this.ScenarioSetup(scenarioInfo);
#line 16
            this.FeatureBackground();
#line 99
            testRunner.Given("que eu navegue para a Tela de Decupagem Basica", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 100
            testRunner.When("eu faco uma decupagem basica para o periodo Noite", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 101
            testRunner.Then("eu visualizo a Cena criada com periodo noite com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }

        [TechTalk.SpecRun.ScenarioAttribute("14 - Alteração de cena decupada", new string[] {
                "chrome",
                "excluir_NovoCapitulo",
                "logout"}, SourceLine = 103)]
        public virtual void _14_AlteracaoDeCenaDecupada()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("14 - Alteração de cena decupada", new string[] {
                        "chrome",
                        "excluir_NovoCapitulo",
                        "logout"});
#line 104
            this.ScenarioSetup(scenarioInfo);
#line 16
            this.FeatureBackground();
#line 105
            testRunner.Given("que eu tenha uma cena decupada", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 106
            testRunner.When("eu realizo uma alteracao na decupagem basica", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 107
            testRunner.And("eu faco busca por cena em consulta de log", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 108
            testRunner.Then("eu visualizo a alteracao feita no log com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }

        [TechTalk.SpecRun.ScenarioAttribute("15 - Decupagem de cena através de atalho", new string[] {
                "chrome",
                "excluir_NovoCapitulo",
                "logout"}, SourceLine = 110)]
        public virtual void _15_DecupagemDeCenaAtravesDeAtalho()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("15 - Decupagem de cena através de atalho", new string[] {
                        "chrome",
                        "excluir_NovoCapitulo",
                        "logout"});
#line 111
            this.ScenarioSetup(scenarioInfo);
#line 16
            this.FeatureBackground();
#line 112
            testRunner.Given("que eu navegue para a Tela de Decupagem Basica atraves de atalho", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 113
            testRunner.When("eu faco uma decupagem basica preenchendo os novos campos GROT", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 114
            testRunner.Then("eu visualizo os novos campos de decupagem basica com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }

        [TechTalk.SpecRun.ScenarioAttribute("16 - Alteração de cena decupada - limpar preenchimento dos novos campos", new string[] {
                "chrome",
                "excluir_NovoCapitulo",
                "logout"}, SourceLine = 116)]
        public virtual void _16_AlteracaoDeCenaDecupada_LimparPreenchimentoDosNovosCampos()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("16 - Alteração de cena decupada - limpar preenchimento dos novos campos", new string[] {
                        "chrome",
                        "excluir_NovoCapitulo",
                        "logout"});
#line 117
            this.ScenarioSetup(scenarioInfo);
#line 16
            this.FeatureBackground();
#line 118
            testRunner.Given("que eu tenha uma cena decupada", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 119
            testRunner.When("eu edito a cena decupada limpando os campos GROT", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 120
            testRunner.And("eu faco busca por cena em consulta de log", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 121
            testRunner.Then("eu visualizo a alteracao feita no log com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }

        [TechTalk.SpecRun.ScenarioAttribute("17 - Criação e liberação de Roteiro", new string[] {
                "chrome",
                "excluir_PlanejamentoRoteiro",
                "excluir_NovoCapitulo",
                "logout"}, SourceLine = 123)]
        public virtual void _17_CriacaoELiberacaoDeRoteiro()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("17 - Criação e liberação de Roteiro", new string[] {
                        "chrome",
                        "excluir_PlanejamentoRoteiro",
                        "excluir_NovoCapitulo",
                        "logout"});
#line 124
            this.ScenarioSetup(scenarioInfo);
#line 16
            this.FeatureBackground();
#line 125
            testRunner.Given("que eu tenha uma cena decupada", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 126
            testRunner.When("criar um planejamento de roteiro", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 127
            testRunner.Then("visualizo roteiro criado com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }

        [TechTalk.SpecRun.ScenarioAttribute("18 - Alteração de cena para Gravada", new string[] {
                "chrome",
                "alterar_StatusRoteiro",
                "excluir_PlanejamentoRoteiro",
                "excluir_NovoCapitulo",
                "logout"}, SourceLine = 129)]
        public virtual void _18_AlteracaoDeCenaParaGravada()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("18 - Alteração de cena para Gravada", new string[] {
                        "chrome",
                        "alterar_StatusRoteiro",
                        "excluir_PlanejamentoRoteiro",
                        "excluir_NovoCapitulo",
                        "logout"});
#line 130
            this.ScenarioSetup(scenarioInfo);
#line 16
            this.FeatureBackground();
#line 131
            testRunner.Given("que eu tenha uma cena decupada", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 132
            testRunner.And("que eu esteja com planejamento de roteiro realizado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 133
            testRunner.When("Atualizar cena para gravada", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 134
            testRunner.Then("visualizo status do roteiro gravada", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }

        [TechTalk.SpecRun.ScenarioAttribute("19 - Alteração de parâmetro Faixa prevista Gravação (hh:mm) - de - até", new string[] {
                "chrome",
                "excluir_NovoCapitulo",
                "logout"}, SourceLine = 136)]
        public virtual void _19_AlteracaoDeParametroFaixaPrevistaGravacaoHhMm_De_Ate()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("19 - Alteração de parâmetro Faixa prevista Gravação (hh:mm) - de - até", new string[] {
                        "chrome",
                        "excluir_NovoCapitulo",
                        "logout"});
#line 137
            this.ScenarioSetup(scenarioInfo);
#line 16
            this.FeatureBackground();
#line 138
            testRunner.Given("que eu acesse a tela de parametros de producao apos criar um capitulo", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 139
            testRunner.When("eu altero os valores de periodo noturno", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 140
            testRunner.Then("eu visualizo que a alteracao feita nao foi refletida na tela de decupagem basica " +
                               "com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }

        [TechTalk.SpecRun.ScenarioAttribute("20 - Validação de cena após alteração de parâmetro do período \"Noite\"", new string[] {
                "chrome",
                "excluir_NovoCapitulo",
                "logout"}, SourceLine = 142)]
        public virtual void _20_ValidacaoDeCenaAposAlteracaoDeParametroDoPeriodoNoite()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("20 - Validação de cena após alteração de parâmetro do período \"Noite\"", new string[] {
                        "chrome",
                        "excluir_NovoCapitulo",
                        "logout"});
#line 143
            this.ScenarioSetup(scenarioInfo);
#line 16
            this.FeatureBackground();
#line 144
            testRunner.Given("que eu acesse a tela de parametros de producao apos criar um capitulo", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 145
            testRunner.When("eu altero os valores de periodo noturno", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 146
            testRunner.Then("eu visualizo que a alteracao feita nao foi refletida na tela de decupagem basica " +
                               "com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }

        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
