// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Tests.SGP.Features.GROT._01_Bloco01._01_04_DecupagemContinu
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("01.04 - Decupagem continuidade", new string[] {
            "kill_Driver"}, Description="Narrativa:\r\n\tEu como adminstrador do sistema\r\n\tQuero criar um novo Cenário no SGP" +
        "\r\n\tPara ter controle dos Cenários que serão manipulados\r\n\t\r\nFora de escopo:\r\n\tTe" +
        "stes negativos", SourceFile="Features\\GROT\\01 - Bloco 01\\01.04 - DecupagemContinu\\01.04 - DecupagemContinuidad" +
        "e.feature", SourceLine=5)]
    public partial class _01_04_DecupagemContinuidadeFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "01.04 - DecupagemContinuidade.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "01.04 - Decupagem continuidade", "Narrativa:\r\n\tEu como adminstrador do sistema\r\n\tQuero criar um novo Cenário no SGP" +
                    "\r\n\tPara ter controle dos Cenários que serão manipulados\r\n\t\r\nFora de escopo:\r\n\tTe" +
                    "stes negativos", ProgrammingLanguage.CSharp, new string[] {
                        "kill_Driver"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 16
#line 17
 testRunner.Given("que eu navegue para a Tela de Login do SGP", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 18
 testRunner.And("efetuar o login no sistema do SGP", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 19
 testRunner.And("que eu navegue para a Tela Home com a programacao selecionada", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 20
 testRunner.And("que eu criar um capitulo com decupagem", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("01 - Alterar campo de Tempo de preparação de Figurino/caracterização.", new string[] {
                "chrome",
                "excluir_NovoCapitulo",
                "excluir_Roupas",
                "logout"}, SourceLine=22)]
        public virtual void _01_AlterarCampoDeTempoDePreparacaoDeFigurinoCaracterizacao_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("01 - Alterar campo de Tempo de preparação de Figurino/caracterização.", new string[] {
                        "chrome",
                        "excluir_NovoCapitulo",
                        "excluir_Roupas",
                        "logout"});
#line 23
this.ScenarioSetup(scenarioInfo);
#line 16
this.FeatureBackground();
#line 24
 testRunner.Given("que eu navegue para a Tela de Decupagem Continuidade", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 25
 testRunner.When("criar uma decupagem de continuidade grot", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 26
 testRunner.Then("visualizo decupagem de continuidade realizada com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("03 - Validação do novo campo para usuário com perfil GROT", new string[] {
                "chrome",
                "excluir_NovoCapitulo",
                "excluir_Roupas",
                "logout"}, SourceLine=28)]
        public virtual void _03_ValidacaoDoNovoCampoParaUsuarioComPerfilGROT()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("03 - Validação do novo campo para usuário com perfil GROT", new string[] {
                        "chrome",
                        "excluir_NovoCapitulo",
                        "excluir_Roupas",
                        "logout"});
#line 29
this.ScenarioSetup(scenarioInfo);
#line 16
this.FeatureBackground();
#line 30
 testRunner.Given("que eu navegue para a Tela de Decupagem Continuidade", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 31
 testRunner.When("criar uma decupagem de continuidade grot alterando os valores de tempo de prepara" +
                    "cao", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 32
 testRunner.Then("visualizo decupagem de continuidade realizada com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04 - Decupagem de continuidade com preenchimento do novo campo", new string[] {
                "chrome",
                "excluir_NovoCapitulo",
                "excluir_Roupas",
                "logout"}, SourceLine=34)]
        public virtual void _04_DecupagemDeContinuidadeComPreenchimentoDoNovoCampo()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("04 - Decupagem de continuidade com preenchimento do novo campo", new string[] {
                        "chrome",
                        "excluir_NovoCapitulo",
                        "excluir_Roupas",
                        "logout"});
#line 35
this.ScenarioSetup(scenarioInfo);
#line 16
this.FeatureBackground();
#line 36
 testRunner.Given("que eu crie uma decupagem de continuidade com perfil grot", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 37
 testRunner.When("eu faco busca por cena em consulta de log", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 38
 testRunner.Then("eu visualizo a edicao de decupagem de continuidade com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("05 - Decupagem de continuidade sem preenchimento do novo campo", new string[] {
                "chrome",
                "excluir_NovoCapitulo",
                "excluir_Roupas",
                "logout"}, SourceLine=40)]
        public virtual void _05_DecupagemDeContinuidadeSemPreenchimentoDoNovoCampo()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("05 - Decupagem de continuidade sem preenchimento do novo campo", new string[] {
                        "chrome",
                        "excluir_NovoCapitulo",
                        "excluir_Roupas",
                        "logout"});
#line 41
this.ScenarioSetup(scenarioInfo);
#line 16
this.FeatureBackground();
#line 42
 testRunner.Given("que eu crie uma decupagem de continuidade com perfil grot sem preencher o novo ca" +
                    "mpo", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 43
 testRunner.When("eu faco busca por cena em consulta de log", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 44
 testRunner.Then("eu visualizo a edicao de decupagem de continuidade com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("06 - Alteração de cena decupada removendo preenchimento do campo \"Tempo Preparaçã" +
            "o figurino/caracterização(min)\"", new string[] {
                "chrome",
                "excluir_NovoCapitulo",
                "excluir_Roupas",
                "logout"}, SourceLine=46)]
        public virtual void _06_AlteracaoDeCenaDecupadaRemovendoPreenchimentoDoCampoTempoPreparacaoFigurinoCaracterizacaoMin()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("06 - Alteração de cena decupada removendo preenchimento do campo \"Tempo Preparaçã" +
                    "o figurino/caracterização(min)\"", new string[] {
                        "chrome",
                        "excluir_NovoCapitulo",
                        "excluir_Roupas",
                        "logout"});
#line 47
this.ScenarioSetup(scenarioInfo);
#line 16
this.FeatureBackground();
#line 48
 testRunner.Given("que eu crie uma decupagem de continuidade com perfil grot", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 49
 testRunner.When("eu edito a decupagem de continuidade da cena limpando a informacao do campo de te" +
                    "mpo preparacao", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 50
 testRunner.Then("eu visualizo as alteracoes de decupagem de continuidade realizada com sucesso no " +
                    "log do sistema", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("07 - Alteração de cena decupada  preenchendo o campo \"Tempo Preparação figurino/c" +
            "aracterização(min)\"", new string[] {
                "chrome",
                "excluir_NovoCapitulo",
                "excluir_Roupas",
                "logout"}, SourceLine=52)]
        public virtual void _07_AlteracaoDeCenaDecupadaPreenchendoOCampoTempoPreparacaoFigurinoCaracterizacaoMin()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("07 - Alteração de cena decupada  preenchendo o campo \"Tempo Preparação figurino/c" +
                    "aracterização(min)\"", new string[] {
                        "chrome",
                        "excluir_NovoCapitulo",
                        "excluir_Roupas",
                        "logout"});
#line 53
this.ScenarioSetup(scenarioInfo);
#line 16
this.FeatureBackground();
#line 54
 testRunner.Given("que eu crie uma decupagem de continuidade com perfil grot", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 55
 testRunner.When("eu edito a decupagem de continuidade da cena alterando a informacao do campo de t" +
                    "empo preparacao", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 56
 testRunner.Then("eu visualizo as alteracoes de decupagem de continuidade realizada com sucesso no " +
                    "log do sistema", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("08 - Decupagem de continuidade com preenchimento do novo campo - Incluir novo Per" +
            "sonagem", new string[] {
                "chrome",
                "excluir_NovoCapitulo",
                "excluir_Roupas",
                "logout"}, SourceLine=58)]
        public virtual void _08_DecupagemDeContinuidadeComPreenchimentoDoNovoCampo_IncluirNovoPersonagem()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("08 - Decupagem de continuidade com preenchimento do novo campo - Incluir novo Per" +
                    "sonagem", new string[] {
                        "chrome",
                        "excluir_NovoCapitulo",
                        "excluir_Roupas",
                        "logout"});
#line 59
this.ScenarioSetup(scenarioInfo);
#line 16
this.FeatureBackground();
#line 60
 testRunner.Given("que eu crie uma decupagem de continuidade com perfil grot", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 61
 testRunner.When("eu edito a decupagem de continuidade da cena alterando a informacao do campo de t" +
                    "empo preparacao", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 62
 testRunner.And("incluir personagem", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 63
 testRunner.Then("eu visualizo as alteracoes de decupagem de continuidade realizada com sucesso no " +
                    "log do sistema", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("09 - Decupagem de continuidade através de atalho com preenchimento do novo campo", new string[] {
                "chrome",
                "excluir_NovoCapitulo",
                "excluir_Roupas",
                "logout"}, SourceLine=65)]
        public virtual void _09_DecupagemDeContinuidadeAtravesDeAtalhoComPreenchimentoDoNovoCampo()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("09 - Decupagem de continuidade através de atalho com preenchimento do novo campo", new string[] {
                        "chrome",
                        "excluir_NovoCapitulo",
                        "excluir_Roupas",
                        "logout"});
#line 66
this.ScenarioSetup(scenarioInfo);
#line 16
this.FeatureBackground();
#line 67
 testRunner.Given("que eu crie uma decupagem de continuidade com perfil grot atraves do atalho na te" +
                    "la de capitulos e cenas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 68
 testRunner.When("eu faco busca por cena em consulta de log", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 69
 testRunner.Then("eu visualizo a edicao de decupagem de continuidade com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
