// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Tests.SGP.Features.GROT._01_Bloco01._01_07_IndispElenco
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("01.07 - Indisponibilidade de elenco", new string[] {
            "kill_Driver"}, Description="Narrativa:\r\n\tEu como adminstrador do sistema\r\n\tQuero acessar a tela de Indisponib" +
        "ilidade de Elenco\r\n\tPara ter controle da Indisponibilidade de Elenco cadastrados" +
        " no sistema", SourceFile="Features\\GROT\\01 - Bloco 01\\01.07 - IndispElenco\\01.07 - IndisponibilidadeElenco." +
        "feature", SourceLine=6)]
    public partial class _01_07_IndisponibilidadeDeElencoFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "01.07 - IndisponibilidadeElenco.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "01.07 - Indisponibilidade de elenco", "Narrativa:\r\n\tEu como adminstrador do sistema\r\n\tQuero acessar a tela de Indisponib" +
                    "ilidade de Elenco\r\n\tPara ter controle da Indisponibilidade de Elenco cadastrados" +
                    " no sistema", ProgrammingLanguage.CSharp, new string[] {
                        "kill_Driver"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 14
#line 15
 testRunner.Given("que eu navegue para a Tela de Login do SGP", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 16
 testRunner.And("efetuar o login no sistema do SGP", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 17
 testRunner.And("que eu navegue para a Tela Home com a programacao selecionada", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("01 - Filtrar Indisponibilidade de Elenco - Filtro por Personagem/Ator", new string[] {
                "chrome",
                "excluir_IndisponibilidadeElenco",
                "logout"}, SourceLine=20)]
        public virtual void _01_FiltrarIndisponibilidadeDeElenco_FiltroPorPersonagemAtor()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("01 - Filtrar Indisponibilidade de Elenco - Filtro por Personagem/Ator", new string[] {
                        "chrome",
                        "excluir_IndisponibilidadeElenco",
                        "logout"});
#line 21
this.ScenarioSetup(scenarioInfo);
#line 14
this.FeatureBackground();
#line 22
 testRunner.Given("que eu acesse a tela de indisponibilidade de elenco", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 23
 testRunner.And("que eu tenho uma indisponibilidade de elenco cadastrada", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 24
 testRunner.When("eu faco busca por nome de elenco indisponivel", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 25
 testRunner.Then("eu visualizo a indisponibilidade de elenco cadastrada com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("02 - Filtro por Dia da Semana", new string[] {
                "chrome",
                "excluir_IndisponibilidadeElenco",
                "logout"}, SourceLine=27)]
        public virtual void _02_FiltroPorDiaDaSemana()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("02 - Filtro por Dia da Semana", new string[] {
                        "chrome",
                        "excluir_IndisponibilidadeElenco",
                        "logout"});
#line 28
this.ScenarioSetup(scenarioInfo);
#line 14
this.FeatureBackground();
#line 29
 testRunner.Given("que eu acesse a tela de indisponibilidade de elenco", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 30
 testRunner.And("que eu tenho uma indisponibilidade de elenco cadastrada", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 31
 testRunner.When("eu faco busca por dia da semana de elenco indisponivel", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 32
 testRunner.Then("eu visualizo a indisponibilidade de elenco cadastrada com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("03 - Listagem de Indisponibilidade do Elenco", new string[] {
                "chrome",
                "excluir_IndisponibilidadeElenco",
                "logout"}, SourceLine=34)]
        public virtual void _03_ListagemDeIndisponibilidadeDoElenco()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("03 - Listagem de Indisponibilidade do Elenco", new string[] {
                        "chrome",
                        "excluir_IndisponibilidadeElenco",
                        "logout"});
#line 35
this.ScenarioSetup(scenarioInfo);
#line 14
this.FeatureBackground();
#line 36
 testRunner.Given("que eu acesse a tela de indisponibilidade de elenco", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 37
 testRunner.Then("eu visualizo a listagem de indisponibilidade de elenco com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04 - Alteração e Exclusão de Indisponibilidade de Elenco", new string[] {
                "chrome",
                "excluir_IndisponibilidadeElenco",
                "logout"}, SourceLine=39)]
        public virtual void _04_AlteracaoEExclusaoDeIndisponibilidadeDeElenco()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("04 - Alteração e Exclusão de Indisponibilidade de Elenco", new string[] {
                        "chrome",
                        "excluir_IndisponibilidadeElenco",
                        "logout"});
#line 40
this.ScenarioSetup(scenarioInfo);
#line 14
this.FeatureBackground();
#line 41
 testRunner.Given("que eu acesse a tela de indisponibilidade de elenco", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 42
 testRunner.When("eu altero uma indisponibilidade de elenco cadastrada", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 43
 testRunner.Then("eu visualizo a indisponibilidade de elenco alterada com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("05 - Criação de nova Indisponibilidade de Elenco", new string[] {
                "chrome",
                "excluir_IndisponibilidadeElenco",
                "logout"}, SourceLine=45)]
        public virtual void _05_CriacaoDeNovaIndisponibilidadeDeElenco()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("05 - Criação de nova Indisponibilidade de Elenco", new string[] {
                        "chrome",
                        "excluir_IndisponibilidadeElenco",
                        "logout"});
#line 46
this.ScenarioSetup(scenarioInfo);
#line 14
this.FeatureBackground();
#line 47
 testRunner.Given("que eu acesse a tela de indisponibilidade de elenco", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 48
 testRunner.When("eu cadastro uma nova indisponibilidade de elenco", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 49
 testRunner.Then("eu visualizo a indisponibilidade de elenco cadastrada com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("07 - Associar Elenco ao Personagem", new string[] {
                "chrome",
                "excluir_NovoPersonagem",
                "logout"}, SourceLine=51)]
        public virtual void _07_AssociarElencoAoPersonagem()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("07 - Associar Elenco ao Personagem", new string[] {
                        "chrome",
                        "excluir_NovoPersonagem",
                        "logout"});
#line 52
this.ScenarioSetup(scenarioInfo);
#line 14
this.FeatureBackground();
#line 53
 testRunner.Given("que eu navegue para a Tela Personagem", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 54
 testRunner.When("eu criar um novo personagem", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 55
 testRunner.Then("eu visualizo novo personagem criado com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
