// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Tests.SGP.Features.SGROT._03_CapitulosECenas._03_06_FiltrosDeCapitulos
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("03.06 - Filtros", new string[] {
            "kill_Driver"}, Description="Narrativa:\r\n\tEu como adminstrador do sistema\r\n\tQuero filtrar as cenas roteirizáve" +
        "is no SGP\r\n\tPara ter controle dos Capítulos e Cenas que serão roterizados\r\n\t\r\nFo" +
        "ra de escopo:\r\n\tTestes negativos", SourceFile="Features\\SGROT\\03 - Capítulos e cenas\\03.06 - Filtros de capitulos\\01-ValidarPesq" +
        "uisas.feature", SourceLine=7)]
    public partial class _03_06_FiltrosFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "01-ValidarPesquisas.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "03.06 - Filtros", "Narrativa:\r\n\tEu como adminstrador do sistema\r\n\tQuero filtrar as cenas roteirizáve" +
                    "is no SGP\r\n\tPara ter controle dos Capítulos e Cenas que serão roterizados\r\n\t\r\nFo" +
                    "ra de escopo:\r\n\tTestes negativos", ProgrammingLanguage.CSharp, new string[] {
                        "kill_Driver"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 18
#line 19
 testRunner.Given("que eu navegue para a Tela de Login do SGP", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 20
 testRunner.And("efetuar o login no sistema do SGP com perfil sem GROT", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 21
 testRunner.And("que eu navegue para a Tela Home com a programacao selecionada", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("01 - Validar pesquisa de capitulos - Filtro por capitulo", new string[] {
                "chrome",
                "excluir_NovoCapitulo",
                "logout"}, SourceLine=24)]
        public virtual void _01_ValidarPesquisaDeCapitulos_FiltroPorCapitulo()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("01 - Validar pesquisa de capitulos - Filtro por capitulo", new string[] {
                        "chrome",
                        "excluir_NovoCapitulo",
                        "logout"});
#line 25
this.ScenarioSetup(scenarioInfo);
#line 18
this.FeatureBackground();
#line 26
 testRunner.Given("que eu navegue para a Tela Capitulos e Cenas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 27
 testRunner.When("eu criar um novo capitulo com decupagem", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 28
 testRunner.And("filtrar por capitulos", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 29
 testRunner.Then("visualizo a pesquisa escolhida com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("02 - Validar pesquisa de capitulos - Filtro por intervalo de capitulo", new string[] {
                "chrome",
                "excluir_NovoCapitulo",
                "logout"}, SourceLine=31)]
        public virtual void _02_ValidarPesquisaDeCapitulos_FiltroPorIntervaloDeCapitulo()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("02 - Validar pesquisa de capitulos - Filtro por intervalo de capitulo", new string[] {
                        "chrome",
                        "excluir_NovoCapitulo",
                        "logout"});
#line 32
this.ScenarioSetup(scenarioInfo);
#line 18
this.FeatureBackground();
#line 33
 testRunner.Given("que eu navegue para a Tela Capitulos e Cenas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 34
 testRunner.When("eu criar um novo capitulo com decupagem", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 35
 testRunner.And("filtrar por capitulos com intervalo", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 36
 testRunner.Then("visualizo a pesquisa escolhida com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("03 - Validar pesquisa de capitulos - Filtro por capitulos e cenas", new string[] {
                "chrome",
                "excluir_NovoCapitulo",
                "logout"}, SourceLine=38)]
        public virtual void _03_ValidarPesquisaDeCapitulos_FiltroPorCapitulosECenas()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("03 - Validar pesquisa de capitulos - Filtro por capitulos e cenas", new string[] {
                        "chrome",
                        "excluir_NovoCapitulo",
                        "logout"});
#line 39
this.ScenarioSetup(scenarioInfo);
#line 18
this.FeatureBackground();
#line 40
 testRunner.Given("que eu navegue para a Tela Capitulos e Cenas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 41
 testRunner.When("eu criar um novo capitulo com decupagem", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 42
 testRunner.And("filtrar por capitulos e cenas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 43
 testRunner.Then("visualizo a pesquisa escolhida com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04 - Validar pesquisa de capitulos - Filtro por capitulo e intervalo de cenas", new string[] {
                "chrome",
                "excluir_NovoCapitulo",
                "logout"}, SourceLine=45)]
        public virtual void _04_ValidarPesquisaDeCapitulos_FiltroPorCapituloEIntervaloDeCenas()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("04 - Validar pesquisa de capitulos - Filtro por capitulo e intervalo de cenas", new string[] {
                        "chrome",
                        "excluir_NovoCapitulo",
                        "logout"});
#line 46
this.ScenarioSetup(scenarioInfo);
#line 18
this.FeatureBackground();
#line 47
 testRunner.Given("que eu navegue para a Tela Capitulos e Cenas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 48
 testRunner.When("eu criar um novo capitulo com decupagem", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 49
 testRunner.And("filtrar por capitulos e intervalo de cenas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 50
 testRunner.Then("visualizo a pesquisa escolhida com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("05 - Validar pesquisa de capitulos - Filtro por datas de roteiro", new string[] {
                "chrome",
                "excluir_PlanejamentoRoteiro",
                "excluir_NovoCapitulo",
                "logout"}, SourceLine=52)]
        public virtual void _05_ValidarPesquisaDeCapitulos_FiltroPorDatasDeRoteiro()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("05 - Validar pesquisa de capitulos - Filtro por datas de roteiro", new string[] {
                        "chrome",
                        "excluir_PlanejamentoRoteiro",
                        "excluir_NovoCapitulo",
                        "logout"});
#line 53
this.ScenarioSetup(scenarioInfo);
#line 18
this.FeatureBackground();
#line 54
 testRunner.Given("que eu navegue para a Tela Capitulos e Cenas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 55
 testRunner.When("eu criar um novo capitulo com decupagem", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 56
 testRunner.Given("que eu esteja com planejamento de roteiro realizado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 57
 testRunner.And("que eu navegue para a Tela Capitulos e Cenas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 58
 testRunner.And("filtrar capitulo por datas de roteitros", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 59
 testRunner.Then("visualizo a pesquisa escolhida com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("06 - Validar pesquisa de capitulos - Filtro por categoria", new string[] {
                "chrome",
                "excluir_NovoCapitulo",
                "logout"}, SourceLine=61)]
        public virtual void _06_ValidarPesquisaDeCapitulos_FiltroPorCategoria()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("06 - Validar pesquisa de capitulos - Filtro por categoria", new string[] {
                        "chrome",
                        "excluir_NovoCapitulo",
                        "logout"});
#line 62
this.ScenarioSetup(scenarioInfo);
#line 18
this.FeatureBackground();
#line 63
 testRunner.Given("que eu navegue para a Tela Capitulos e Cenas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 64
 testRunner.When("eu criar um novo capitulo com decupagem", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 65
 testRunner.And("filtrar capitulos por categoria", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 66
 testRunner.Then("visualizo a pesquisa escolhida com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("07 - Validar pesquisa de capitulos - Filtro por cenario", new string[] {
                "chrome",
                "excluir_NovoCapitulo",
                "logout"}, SourceLine=68)]
        public virtual void _07_ValidarPesquisaDeCapitulos_FiltroPorCenario()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("07 - Validar pesquisa de capitulos - Filtro por cenario", new string[] {
                        "chrome",
                        "excluir_NovoCapitulo",
                        "logout"});
#line 69
this.ScenarioSetup(scenarioInfo);
#line 18
this.FeatureBackground();
#line 70
 testRunner.Given("que eu navegue para a Tela Capitulos e Cenas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 71
 testRunner.When("eu criar um novo capitulo com decupagem", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 72
 testRunner.And("filtrar capitulos por cenario", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 73
 testRunner.Then("visualizo a pesquisa escolhida com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("08 - Validar pesquisa de capitulos - Filtro por cenario e ambiente", new string[] {
                "chrome",
                "excluir_NovoCapitulo",
                "logout"}, SourceLine=75)]
        public virtual void _08_ValidarPesquisaDeCapitulos_FiltroPorCenarioEAmbiente()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("08 - Validar pesquisa de capitulos - Filtro por cenario e ambiente", new string[] {
                        "chrome",
                        "excluir_NovoCapitulo",
                        "logout"});
#line 76
this.ScenarioSetup(scenarioInfo);
#line 18
this.FeatureBackground();
#line 77
 testRunner.Given("que eu navegue para a Tela Capitulos e Cenas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 78
 testRunner.When("eu criar um novo capitulo com decupagem", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 79
 testRunner.And("filtrar capitulos por cenario e ambiente", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 80
 testRunner.Then("visualizo a pesquisa escolhida com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("09 - Validar pesquisa de capitulos - Filtro por numeros de roteiros", new string[] {
                "chrome",
                "excluir_PlanejamentoRoteiro",
                "excluir_NovoCapitulo",
                "logout"}, SourceLine=82)]
        public virtual void _09_ValidarPesquisaDeCapitulos_FiltroPorNumerosDeRoteiros()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("09 - Validar pesquisa de capitulos - Filtro por numeros de roteiros", new string[] {
                        "chrome",
                        "excluir_PlanejamentoRoteiro",
                        "excluir_NovoCapitulo",
                        "logout"});
#line 83
this.ScenarioSetup(scenarioInfo);
#line 18
this.FeatureBackground();
#line 84
 testRunner.Given("que eu navegue para a Tela Capitulos e Cenas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 85
 testRunner.When("eu criar um novo capitulo com decupagem", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 86
 testRunner.Given("que eu esteja com planejamento de roteiro realizado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 88
 testRunner.And("filtrar capitulos por numeros de roteiros", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 89
 testRunner.Then("visualizo a pesquisa escolhida com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("10 - Validar pesquisa de capitulos - Filtro por status", new string[] {
                "chrome",
                "excluir_NovoCapitulo",
                "logout"}, SourceLine=91)]
        public virtual void _10_ValidarPesquisaDeCapitulos_FiltroPorStatus()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("10 - Validar pesquisa de capitulos - Filtro por status", new string[] {
                        "chrome",
                        "excluir_NovoCapitulo",
                        "logout"});
#line 92
this.ScenarioSetup(scenarioInfo);
#line 18
this.FeatureBackground();
#line 93
 testRunner.Given("que eu navegue para a Tela Capitulos e Cenas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 94
 testRunner.When("eu criar um novo capitulo com decupagem", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 95
 testRunner.And("filtrar capitulos por status", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 96
 testRunner.Then("visualizo a pesquisa escolhida com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("11 - Validar pesquisa de capitulos - Filtro por tipo", new string[] {
                "chrome",
                "excluir_NovoCapitulo",
                "logout"}, SourceLine=98)]
        public virtual void _11_ValidarPesquisaDeCapitulos_FiltroPorTipo()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("11 - Validar pesquisa de capitulos - Filtro por tipo", new string[] {
                        "chrome",
                        "excluir_NovoCapitulo",
                        "logout"});
#line 99
this.ScenarioSetup(scenarioInfo);
#line 18
this.FeatureBackground();
#line 100
 testRunner.Given("que eu navegue para a Tela Capitulos e Cenas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 101
 testRunner.When("eu criar um novo capitulo com decupagem", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 102
 testRunner.And("filtrar capitulos por tipo", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 103
 testRunner.Then("visualizo a pesquisa escolhida com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("12 - Validar pesquisa de capitulos - Filtro por dois campos de filtros", new string[] {
                "chrome",
                "excluir_NovoCapitulo",
                "logout"}, SourceLine=105)]
        public virtual void _12_ValidarPesquisaDeCapitulos_FiltroPorDoisCamposDeFiltros()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("12 - Validar pesquisa de capitulos - Filtro por dois campos de filtros", new string[] {
                        "chrome",
                        "excluir_NovoCapitulo",
                        "logout"});
#line 106
this.ScenarioSetup(scenarioInfo);
#line 18
this.FeatureBackground();
#line 107
 testRunner.Given("que eu navegue para a Tela Capitulos e Cenas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 108
 testRunner.When("eu criar um novo capitulo com decupagem", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 109
 testRunner.And("filtrar capitulos com dois campos", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 110
 testRunner.Then("visualizo a pesquisa escolhida com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("13 - Validar pesquisa de capitulos - Filtro por tres campos de filtros", new string[] {
                "chrome",
                "excluir_NovoCapitulo",
                "logout"}, SourceLine=112)]
        public virtual void _13_ValidarPesquisaDeCapitulos_FiltroPorTresCamposDeFiltros()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("13 - Validar pesquisa de capitulos - Filtro por tres campos de filtros", new string[] {
                        "chrome",
                        "excluir_NovoCapitulo",
                        "logout"});
#line 113
this.ScenarioSetup(scenarioInfo);
#line 18
this.FeatureBackground();
#line 114
 testRunner.Given("que eu navegue para a Tela Capitulos e Cenas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 115
 testRunner.When("eu criar um novo capitulo com decupagem", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 116
 testRunner.And("filtrar capitulos com tres campos", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 117
 testRunner.Then("visualizo a pesquisa escolhida com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("14 - Validar pesquisa de capitulos - Campos avançados - mat. com marc. de cena", new string[] {
                "chrome",
                "excluir_NovoCapitulo",
                "logout"}, SourceLine=119)]
        public virtual void _14_ValidarPesquisaDeCapitulos_CamposAvancados_Mat_ComMarc_DeCena()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("14 - Validar pesquisa de capitulos - Campos avançados - mat. com marc. de cena", new string[] {
                        "chrome",
                        "excluir_NovoCapitulo",
                        "logout"});
#line 120
this.ScenarioSetup(scenarioInfo);
#line 18
this.FeatureBackground();
#line 121
 testRunner.Given("que eu navegue para a Tela Capitulos e Cenas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 122
 testRunner.When("eu criar um novo capitulo com decupagem", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 123
 testRunner.And("filtrar capitulos com materias e marcacao de cena", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 124
 testRunner.Then("visualizo a pesquisa de materias de cena escolhido com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("15 - Validar pesquisa de capitulos - Campos avançados - apenas capitulos secretos" +
            "", new string[] {
                "chrome",
                "excluir_NovoCapitulo",
                "logout"}, SourceLine=126)]
        public virtual void _15_ValidarPesquisaDeCapitulos_CamposAvancados_ApenasCapitulosSecretos()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("15 - Validar pesquisa de capitulos - Campos avançados - apenas capitulos secretos" +
                    "", new string[] {
                        "chrome",
                        "excluir_NovoCapitulo",
                        "logout"});
#line 127
this.ScenarioSetup(scenarioInfo);
#line 18
this.FeatureBackground();
#line 128
 testRunner.Given("que eu navegue para a Tela Capitulos e Cenas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 129
 testRunner.When("eu criar um Novo Capitulo secreto", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 130
 testRunner.And("filtrar capitulos por capitulo secreto", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 131
 testRunner.Then("visualizo a pesquisa escolhida com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("16 - Validar pesquisa de capitulos - Campos avançados - apenas cenas secretas", new string[] {
                "chrome",
                "excluir_NovoCapitulo",
                "logout"}, SourceLine=133)]
        public virtual void _16_ValidarPesquisaDeCapitulos_CamposAvancados_ApenasCenasSecretas()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("16 - Validar pesquisa de capitulos - Campos avançados - apenas cenas secretas", new string[] {
                        "chrome",
                        "excluir_NovoCapitulo",
                        "logout"});
#line 134
this.ScenarioSetup(scenarioInfo);
#line 18
this.FeatureBackground();
#line 135
 testRunner.Given("que eu criar um novo capitulo", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 136
 testRunner.When("eu criar uma cena secreta", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 137
 testRunner.And("filtrar capitulos por cena secreta", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 138
 testRunner.Then("visualizo a pesquisa escolhida com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("17 - Validar pesquisa de capitulos - Campos avançados - todos os capitulos", new string[] {
                "chrome",
                "excluir_NovoCapitulo",
                "logout"}, SourceLine=140)]
        public virtual void _17_ValidarPesquisaDeCapitulos_CamposAvancados_TodosOsCapitulos()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("17 - Validar pesquisa de capitulos - Campos avançados - todos os capitulos", new string[] {
                        "chrome",
                        "excluir_NovoCapitulo",
                        "logout"});
#line 141
this.ScenarioSetup(scenarioInfo);
#line 18
this.FeatureBackground();
#line 142
 testRunner.Given("que eu navegue para a Tela Capitulos e Cenas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 143
 testRunner.When("eu criar um novo capitulo com decupagem", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 144
 testRunner.And("filtrar capitulos por capitulo e cena opcao todos", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 145
 testRunner.Then("visualizo a pesquisa escolhida com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("18 - Validar pesquisa de capitulos - Campos avançados - mat. prioritario", new string[] {
                "chrome",
                "excluir_NovoCapitulo",
                "logout"}, SourceLine=147)]
        public virtual void _18_ValidarPesquisaDeCapitulos_CamposAvancados_Mat_Prioritario()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("18 - Validar pesquisa de capitulos - Campos avançados - mat. prioritario", new string[] {
                        "chrome",
                        "excluir_NovoCapitulo",
                        "logout"});
#line 148
this.ScenarioSetup(scenarioInfo);
#line 18
this.FeatureBackground();
#line 149
 testRunner.Given("que eu navegue para a Tela Capitulos e Cenas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 150
 testRunner.When("eu criar um novo capitulo com decupagem", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 151
 testRunner.And("filtrar capitulos por material prioritario", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 152
 testRunner.Then("visualizo a pesquisa de materias de cena escolhido com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("19 - Validar pesquisa de capitulos - Campos avançados - classificacao", new string[] {
                "chrome",
                "excluir_NovoCapitulo",
                "logout"}, SourceLine=154)]
        public virtual void _19_ValidarPesquisaDeCapitulos_CamposAvancados_Classificacao()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("19 - Validar pesquisa de capitulos - Campos avançados - classificacao", new string[] {
                        "chrome",
                        "excluir_NovoCapitulo",
                        "logout"});
#line 155
this.ScenarioSetup(scenarioInfo);
#line 18
this.FeatureBackground();
#line 156
 testRunner.Given("que eu navegue para a Tela Capitulos e Cenas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 157
 testRunner.When("eu criar um novo capitulo com decupagem", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 158
 testRunner.And("filtrar capitulos por classificacao", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 159
 testRunner.Then("visualizo a pesquisa escolhida com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("20 - Validar pesquisa de capitulos - Filtro por personagem", new string[] {
                "chrome",
                "excluir_NovoCapitulo",
                "logout"}, SourceLine=161)]
        public virtual void _20_ValidarPesquisaDeCapitulos_FiltroPorPersonagem()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("20 - Validar pesquisa de capitulos - Filtro por personagem", new string[] {
                        "chrome",
                        "excluir_NovoCapitulo",
                        "logout"});
#line 162
this.ScenarioSetup(scenarioInfo);
#line 18
this.FeatureBackground();
#line 163
 testRunner.Given("que eu navegue para a Tela Capitulos e Cenas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 164
 testRunner.When("eu criar um novo capitulo com decupagem", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 165
 testRunner.And("filtrar capitulos por personagem", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 166
 testRunner.Then("visualizo a pesquisa escolhida com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("21 - Validar pesquisa de capitulos - Filtro por figurante", new string[] {
                "chrome",
                "excluir_NovoCapitulo",
                "logout"}, SourceLine=168)]
        public virtual void _21_ValidarPesquisaDeCapitulos_FiltroPorFigurante()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("21 - Validar pesquisa de capitulos - Filtro por figurante", new string[] {
                        "chrome",
                        "excluir_NovoCapitulo",
                        "logout"});
#line 169
this.ScenarioSetup(scenarioInfo);
#line 18
this.FeatureBackground();
#line 170
 testRunner.Given("que eu navegue para a Tela Capitulos e Cenas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 171
 testRunner.When("eu criar um novo capitulo com decupagem", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 172
 testRunner.And("filtrar capitulos por figurante", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 173
 testRunner.Then("visualizo a pesquisa escolhida com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("22 - Validar pesquisa de capitulos - Filtro por periodo do dia", new string[] {
                "chrome",
                "excluir_NovoCapitulo",
                "logout"}, SourceLine=175)]
        public virtual void _22_ValidarPesquisaDeCapitulos_FiltroPorPeriodoDoDia()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("22 - Validar pesquisa de capitulos - Filtro por periodo do dia", new string[] {
                        "chrome",
                        "excluir_NovoCapitulo",
                        "logout"});
#line 176
this.ScenarioSetup(scenarioInfo);
#line 18
this.FeatureBackground();
#line 177
 testRunner.Given("que eu navegue para a Tela Capitulos e Cenas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 178
 testRunner.When("eu criar um novo capitulo com decupagem", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 179
 testRunner.And("filtrar capitulos por periodo do dia", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 180
 testRunner.Then("visualizo a pesquisa escolhida com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("23 - Validar pesquisa de capitulos - Filtro por tipo do cenario", new string[] {
                "chrome",
                "excluir_NovoCapitulo",
                "logout"}, SourceLine=182)]
        public virtual void _23_ValidarPesquisaDeCapitulos_FiltroPorTipoDoCenario()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("23 - Validar pesquisa de capitulos - Filtro por tipo do cenario", new string[] {
                        "chrome",
                        "excluir_NovoCapitulo",
                        "logout"});
#line 183
this.ScenarioSetup(scenarioInfo);
#line 18
this.FeatureBackground();
#line 184
 testRunner.Given("que eu navegue para a Tela Capitulos e Cenas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 185
 testRunner.When("eu criar um novo capitulo com decupagem", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 186
 testRunner.And("filtrar capitulos por tipo do cenario", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 187
 testRunner.Then("visualizo a pesquisa escolhida com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
