// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Tests.SGP.Features.GROT._02_Bloco02._01_GrupoDeGravacao
{
    using TechTalk.SpecFlow;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("02.01 - Grupo de gravação", new string[] {
            "kill_Driver"}, Description = "Narrativa:\r\n\tEu como adminstrador do sistema\r\n\tQuero acessar a tela de Grupo Loca" +
        "l de Gravação\r\n\tPara ter controle dos locais criados e seus respectivos deslocam" +
        "entos", SourceFile = "Features\\GROT\\02 - Bloco 02\\01 - GrupoDeGravacao\\02.01 - GrupoDeGravacao.feature", SourceLine = 6)]
    public partial class _02_01_GrupoDeGravacaoFeature
    {

        private TechTalk.SpecFlow.ITestRunner testRunner;

#line 1 "02.01 - GrupoDeGravacao.feature"
#line hidden

        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "02.01 - Grupo de gravação", "Narrativa:\r\n\tEu como adminstrador do sistema\r\n\tQuero acessar a tela de Grupo Loca" +
                    "l de Gravação\r\n\tPara ter controle dos locais criados e seus respectivos deslocam" +
                    "entos", ProgrammingLanguage.CSharp, new string[] {
                        "kill_Driver"});
            testRunner.OnFeatureStart(featureInfo);
        }

        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }

        public virtual void TestInitialize()
        {
        }

        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }

        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }

        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }

        public virtual void FeatureBackground()
        {
#line 14
#line 15
            testRunner.Given("que eu navegue para a Tela de Login do SGP", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 16
            testRunner.And("efetuar o login no sistema do SGP", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 17
            testRunner.And("que eu navegue para a Tela Home com a programacao selecionada", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
        }

        [TechTalk.SpecRun.ScenarioAttribute("01 - Listar Deslocamentos - Listagem do local", new string[] {
                "chrome",
                "logout"}, SourceLine = 20)]
        public virtual void _01_ListarDeslocamentos_ListagemDoLocal()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("01 - Listar Deslocamentos - Listagem do local", new string[] {
                        "chrome",
                        "logout"});
#line 21
            this.ScenarioSetup(scenarioInfo);
#line 14
            this.FeatureBackground();
#line 22
            testRunner.Given("que eu acesse a tela de grupo local de gravacao", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 23
            testRunner.When("eu criar um novo local", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 24
            testRunner.Then("eu visualizo o novo local criado com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }

        [TechTalk.SpecRun.ScenarioAttribute("02 - Criar Local", new string[] {
                "chrome",
                "logout"}, SourceLine = 26)]
        public virtual void _02_CriarLocal()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("02 - Criar Local", new string[] {
                        "chrome",
                        "logout"});
#line 27
            this.ScenarioSetup(scenarioInfo);
#line 14
            this.FeatureBackground();
#line 28
            testRunner.Given("que eu acesse a tela de grupo local de gravacao", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 29
            testRunner.When("eu criar um novo local", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 30
            testRunner.Then("eu visualizo o novo local criado com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }

        [TechTalk.SpecRun.ScenarioAttribute("03 - Exclusão do Local", new string[] {
                "chrome",
                "logout"}, SourceLine = 32)]
        public virtual void _03_ExclusaoDoLocal()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("03 - Exclusão do Local", new string[] {
                        "chrome",
                        "logout"});
#line 33
            this.ScenarioSetup(scenarioInfo);
#line 14
            this.FeatureBackground();
#line 34
            testRunner.Given("que eu acesse a tela de grupo local de gravacao", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 35
            testRunner.When("eu excluo um local com capitulo associado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 36
            testRunner.Then("eu visualizo a mensagem de critica com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }

        [TechTalk.SpecRun.ScenarioAttribute("04 - Filtro por Local de Gravação A", new string[] {
                "chrome",
                "logout"}, SourceLine = 38)]
        public virtual void _04_FiltroPorLocalDeGravacaoA()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("04 - Filtro por Local de Gravação A", new string[] {
                        "chrome",
                        "logout"});
#line 39
            this.ScenarioSetup(scenarioInfo);
#line 14
            this.FeatureBackground();
#line 40
            testRunner.Given("que eu acesse a tela de grupo local de gravacao", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 41
            testRunner.When("eu faco um filtro por local de gravacao A", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 42
            testRunner.Then("eu visualizo o resultado do filtro por local de gravacao A com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }

        [TechTalk.SpecRun.ScenarioAttribute("05 - Filtro por Local de Gravação B", new string[] {
                "chrome",
                "logout"}, SourceLine = 44)]
        public virtual void _05_FiltroPorLocalDeGravacaoB()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("05 - Filtro por Local de Gravação B", new string[] {
                        "chrome",
                        "logout"});
#line 45
            this.ScenarioSetup(scenarioInfo);
#line 14
            this.FeatureBackground();
#line 46
            testRunner.Given("que eu acesse a tela de grupo local de gravacao", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 47
            testRunner.When("eu faco um filtro por local de gravacao B", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 48
            testRunner.Then("eu visualizo o resultado do filtro por local de gravacao B com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }

        [TechTalk.SpecRun.ScenarioAttribute("06 - Filtro por Grupo Local de Gravação", new string[] {
                "chrome",
                "logout"}, SourceLine = 50)]
        public virtual void _06_FiltroPorGrupoLocalDeGravacao()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("06 - Filtro por Grupo Local de Gravação", new string[] {
                        "chrome",
                        "logout"});
#line 51
            this.ScenarioSetup(scenarioInfo);
#line 14
            this.FeatureBackground();
#line 52
            testRunner.Given("que eu acesse a tela de grupo local de gravacao", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 53
            testRunner.When("eu faco um filtro por grupo local de gravacao", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 54
            testRunner.Then("eu visualizo o resultado do filtro por grupo local de gravacao com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }

        [TechTalk.SpecRun.ScenarioAttribute("07 - Detalhar Local", new string[] {
                "chrome",
                "logout"}, SourceLine = 56)]
        public virtual void _07_DetalharLocal()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("07 - Detalhar Local", new string[] {
                        "chrome",
                        "logout"});
#line 57
            this.ScenarioSetup(scenarioInfo);
#line 14
            this.FeatureBackground();
#line 58
            testRunner.Given("que eu acesse a tela de grupo local de gravacao", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 59
            testRunner.When("eu criar um novo local realizando o seu detalhamento", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 60
            testRunner.Then("eu visualizo o novo local criado com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }

        [TechTalk.SpecRun.ScenarioAttribute("08 - Filtro por Local de Gravação A", new string[] {
                "chrome",
                "logout"}, SourceLine = 62)]
        public virtual void _08_FiltroPorLocalDeGravacaoA()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("08 - Filtro por Local de Gravação A", new string[] {
                        "chrome",
                        "logout"});
#line 63
            this.ScenarioSetup(scenarioInfo);
#line 14
            this.FeatureBackground();
#line 64
            testRunner.Given("que eu acesse a tela de grupo local de gravacao", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 65
            testRunner.When("eu faco um filtro por local de gravacao A", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 66
            testRunner.And("faca uma alteracao", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 67
            testRunner.Then("eu visualizo a mensagem de com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }

        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
