// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Tests.SGP.Features.GROT._03_Bloco03._03_Planejamento
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("03.03 - Utilização da calculadora/Criação roteiro", new string[] {
            "kill_Driver"}, Description="Narrativa:\r\n\tEu como adminstrador do sistema\r\n\tQuero criar e validar um novo rote" +
        "iro no SGP\r\n\tPara ter controle dos Capítulos e Cenas que serão roterizados", SourceFile="Features\\GROT\\03 - Bloco 03\\03 - Planejamento\\03.03 - CriacaoValidacaoRoteiro.fea" +
        "ture", SourceLine=6)]
    public partial class _03_03_UtilizacaoDaCalculadoraCriacaoRoteiroFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "03.03 - CriacaoValidacaoRoteiro.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "03.03 - Utilização da calculadora/Criação roteiro", "Narrativa:\r\n\tEu como adminstrador do sistema\r\n\tQuero criar e validar um novo rote" +
                    "iro no SGP\r\n\tPara ter controle dos Capítulos e Cenas que serão roterizados", ProgrammingLanguage.CSharp, new string[] {
                        "kill_Driver"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 14
#line 15
 testRunner.Given("que eu navegue para a Tela de Login do SGP", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 16
 testRunner.And("efetuar o login no sistema do SGP", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 17
 testRunner.And("que eu navegue para a Tela Home com a programacao selecionada", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 18
 testRunner.And("que eu navegue para a Tela Capitulos e Cenas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("01 - Carregar parâmetros de planejamento de roteiro", new string[] {
                "chrome",
                "excluir_PlanejamentoRoteiro",
                "alterar_ParametroProducao",
                "logout"}, SourceLine=21)]
        public virtual void _01_CarregarParametrosDePlanejamentoDeRoteiro()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("01 - Carregar parâmetros de planejamento de roteiro", new string[] {
                        "chrome",
                        "excluir_PlanejamentoRoteiro",
                        "alterar_ParametroProducao",
                        "logout"});
#line 22
this.ScenarioSetup(scenarioInfo);
#line 14
this.FeatureBackground();
#line 23
 testRunner.Given("que eu preencha o dia de antecedencia na tela de parametro", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 24
 testRunner.When("eu editar data de exibicao do capitulo e criar um roteiro", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 25
 testRunner.Then("eu visualizo alerta de antecedencia minima com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("02 - Criação de roteiro - Cena de capítulo baixo", new string[] {
                "chrome",
                "excluir_PlanejamentoRoteiro",
                "alterar_ParametroProducao",
                "logout"}, SourceLine=27)]
        public virtual void _02_CriacaoDeRoteiro_CenaDeCapituloBaixo()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("02 - Criação de roteiro - Cena de capítulo baixo", new string[] {
                        "chrome",
                        "excluir_PlanejamentoRoteiro",
                        "alterar_ParametroProducao",
                        "logout"});
#line 28
this.ScenarioSetup(scenarioInfo);
#line 14
this.FeatureBackground();
#line 29
 testRunner.Given("que eu preencha o dia de antecedencia na tela de parametro", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 30
 testRunner.When("eu editar data de exibicao do capitulo e criar um roteiro com cena de capitulo ba" +
                    "ixo", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 31
 testRunner.Then("eu visualizo alerta de cena com capitulo baixo com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("03 - Criação de roteiro - Inclusão de cena de capítulo baixo", new string[] {
                "chrome",
                "excluir_PlanejamentoRoteiro",
                "alterar_ParametroProducao",
                "logout"}, SourceLine=33)]
        public virtual void _03_CriacaoDeRoteiro_InclusaoDeCenaDeCapituloBaixo()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("03 - Criação de roteiro - Inclusão de cena de capítulo baixo", new string[] {
                        "chrome",
                        "excluir_PlanejamentoRoteiro",
                        "alterar_ParametroProducao",
                        "logout"});
#line 34
this.ScenarioSetup(scenarioInfo);
#line 14
this.FeatureBackground();
#line 35
 testRunner.Given("que eu preencha o dia de antecedencia na tela de parametro", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 36
 testRunner.When("eu editar data de exibicao do capitulo e criar um roteiro com cena de capitulo ba" +
                    "ixo", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 37
 testRunner.Then("eu visualizo alerta de cena com capitulo baixo com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
