// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Tests.SGP.Features.GROT._03_Bloco03._03_Planejamento
{
    using TechTalk.SpecFlow;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("03.08 - Relatório de Alertas", new string[] {
            "kill_Driver"}, Description = "Narrativa:\r\n\tEu como adminstrador do sistema\r\n\tQuero acessar o Planejamento de Ro" +
        "teiros\r\n\tPara ter controle dos Capítulos e Cenas que serão roterizados", SourceFile = "Features\\GROT\\03 - Bloco 03\\03 - Planejamento\\03.08 - RelatorioAlertas.feature", SourceLine = 6)]
    public partial class _03_08_RelatorioDeAlertasFeature
    {

        private TechTalk.SpecFlow.ITestRunner testRunner;

#line 1 "03.08 - RelatorioAlertas.feature"
#line hidden

        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "03.08 - Relatório de Alertas", "Narrativa:\r\n\tEu como adminstrador do sistema\r\n\tQuero acessar o Planejamento de Ro" +
                    "teiros\r\n\tPara ter controle dos Capítulos e Cenas que serão roterizados", ProgrammingLanguage.CSharp, new string[] {
                        "kill_Driver"});
            testRunner.OnFeatureStart(featureInfo);
        }

        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }

        public virtual void TestInitialize()
        {
        }

        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }

        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }

        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }

        public virtual void FeatureBackground()
        {
#line 14
#line 15
            testRunner.Given("que eu navegue para a Tela de Login do SGP", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 16
            testRunner.And("efetuar o login no sistema do SGP", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 17
            testRunner.And("que eu navegue para a Tela Home com a programacao selecionada", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 18
            testRunner.And("que eu navegue para a Tela Capitulos e Cenas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
        }

        [TechTalk.SpecRun.ScenarioAttribute("01 - Relatório de alertas - Exibição de relatório na tela com GROT", new string[] {
                "chrome",
                "excluir_PlanejamentoRoteiro",
                "logout"}, SourceLine = 21)]
        public virtual void _01_RelatorioDeAlertas_ExibicaoDeRelatorioNaTelaComGROT()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("01 - Relatório de alertas - Exibição de relatório na tela com GROT", new string[] {
                        "chrome",
                        "excluir_PlanejamentoRoteiro",
                        "logout"});
#line 22
            this.ScenarioSetup(scenarioInfo);
#line 14
            this.FeatureBackground();
#line 23
            testRunner.When("que eu crio um roteiro com uma cena externa", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 24
            testRunner.Then("eu visualizo a opcao de relatorio de alertas com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }

        [TechTalk.SpecRun.ScenarioAttribute("02 - Exibição de relatório na tela - Visões do relatório - por alertas", new string[] {
                "chrome",
                "excluir_PlanejamentoRoteiro",
                "logout"}, SourceLine = 26)]
        public virtual void _02_ExibicaoDeRelatorioNaTela_VisoesDoRelatorio_PorAlertas()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("02 - Exibição de relatório na tela - Visões do relatório - por alertas", new string[] {
                        "chrome",
                        "excluir_PlanejamentoRoteiro",
                        "logout"});
#line 27
            this.ScenarioSetup(scenarioInfo);
#line 14
            this.FeatureBackground();
#line 28
            testRunner.When("que eu crio um roteiro com uma cena externa", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 29
            testRunner.Then("eu visualizo a opcao de relatorio de alertas por alertas com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }

        [TechTalk.SpecRun.ScenarioAttribute("03 - Exibição de relatório na tela - Visões do relatório - por período", new string[] {
                "chrome",
                "excluir_PlanejamentoRoteiro",
                "logout"}, SourceLine = 31)]
        public virtual void _03_ExibicaoDeRelatorioNaTela_VisoesDoRelatorio_PorPeriodo()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("03 - Exibição de relatório na tela - Visões do relatório - por período", new string[] {
                        "chrome",
                        "excluir_PlanejamentoRoteiro",
                        "logout"});
#line 32
            this.ScenarioSetup(scenarioInfo);
#line 14
            this.FeatureBackground();
#line 33
            testRunner.When("que eu crio um roteiro com uma cena externa", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 34
            testRunner.Then("eu visualizo a opcao de relatorio de alertas por periodo com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }

        [TechTalk.SpecRun.ScenarioAttribute("04 - Exibição de relatório na tela - Visões do relatório - por período com detalh" +
            "amento", new string[] {
                "chrome",
                "excluir_PlanejamentoRoteiro",
                "logout"}, SourceLine = 36)]
        public virtual void _04_ExibicaoDeRelatorioNaTela_VisoesDoRelatorio_PorPeriodoComDetalhamento()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("04 - Exibição de relatório na tela - Visões do relatório - por período com detalh" +
                    "amento", new string[] {
                        "chrome",
                        "excluir_PlanejamentoRoteiro",
                        "logout"});
#line 37
            this.ScenarioSetup(scenarioInfo);
#line 14
            this.FeatureBackground();
#line 38
            testRunner.When("que eu crio um roteiro com uma cena externa", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 39
            testRunner.Then("eu visualizo a opcao de relatorio de alertas por periodo com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }

        [TechTalk.SpecRun.ScenarioAttribute("05 - Exibição de relatório na tela - Visões do relatório - fechar tela", new string[] {
                "chrome",
                "excluir_PlanejamentoRoteiro",
                "logout"}, SourceLine = 41)]
        public virtual void _05_ExibicaoDeRelatorioNaTela_VisoesDoRelatorio_FecharTela()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("05 - Exibição de relatório na tela - Visões do relatório - fechar tela", new string[] {
                        "chrome",
                        "excluir_PlanejamentoRoteiro",
                        "logout"});
#line 42
            this.ScenarioSetup(scenarioInfo);
#line 14
            this.FeatureBackground();
#line 43
            testRunner.When("que eu crio um roteiro com uma cena externa", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 44
            testRunner.Then("eu visualizo a opcao de relatorio de alertas por periodo com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }

        [TechTalk.SpecRun.ScenarioAttribute("06 - Exibição de relatório na tela - Impressão de todos os alertas", new string[] {
                "chrome",
                "excluir_PlanejamentoRoteiro",
                "logout"}, SourceLine = 46)]
        public virtual void _06_ExibicaoDeRelatorioNaTela_ImpressaoDeTodosOsAlertas()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("06 - Exibição de relatório na tela - Impressão de todos os alertas", new string[] {
                        "chrome",
                        "excluir_PlanejamentoRoteiro",
                        "logout"});
#line 47
            this.ScenarioSetup(scenarioInfo);
#line 14
            this.FeatureBackground();
#line 48
            testRunner.When("que eu crio um roteiro com uma cena externa", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 49
            testRunner.And("faco download do relatorio de alertas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 50
            testRunner.Then("eu visualizo relatorio de alertas com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }

        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
