// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Tests.SGP.Features.GROT._03_Bloco03._03_Planejamento
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("03.11 - Acionamento novas telas", new string[] {
            "kill_Driver"}, Description="Narrativa:\r\n\tEu como adminstrador do sistema\r\n\tQuero acessar as novas telas pelo " +
        "GROT\r\n\tPara ter controle dos Capítulos e Cenas que serão roterizados", SourceFile="Features\\GROT\\03 - Bloco 03\\03 - Planejamento\\03.11 - AcionamentoNovasTelas.featu" +
        "re", SourceLine=6)]
    public partial class _03_11_AcionamentoNovasTelasFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "03.11 - AcionamentoNovasTelas.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "03.11 - Acionamento novas telas", "Narrativa:\r\n\tEu como adminstrador do sistema\r\n\tQuero acessar as novas telas pelo " +
                    "GROT\r\n\tPara ter controle dos Capítulos e Cenas que serão roterizados", ProgrammingLanguage.CSharp, new string[] {
                        "kill_Driver"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 14
#line 15
 testRunner.Given("que eu navegue para a Tela de Login do SGP", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 16
 testRunner.And("efetuar o login no sistema do SGP", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 17
 testRunner.And("que eu navegue para a Tela Home com a programacao selecionada", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 18
 testRunner.And("que eu navegue para a Tela de Planejamento de Roteiros GROT", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("01 - Acionar nova tela de indisponibilidade de elenco GROT", new string[] {
                "chrome",
                "logout"}, SourceLine=21)]
        public virtual void _01_AcionarNovaTelaDeIndisponibilidadeDeElencoGROT()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("01 - Acionar nova tela de indisponibilidade de elenco GROT", new string[] {
                        "chrome",
                        "logout"});
#line 22
this.ScenarioSetup(scenarioInfo);
#line 14
this.FeatureBackground();
#line 23
 testRunner.When("eu acessar a nova tela de indisponibilidade de elenco", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 24
 testRunner.Then("eu visualizo a nova tela de indisponibilidade de elenco com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("02 - Acionar nova tela de local de gravacao GROT", new string[] {
                "chrome",
                "logout"}, SourceLine=26)]
        public virtual void _02_AcionarNovaTelaDeLocalDeGravacaoGROT()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("02 - Acionar nova tela de local de gravacao GROT", new string[] {
                        "chrome",
                        "logout"});
#line 27
this.ScenarioSetup(scenarioInfo);
#line 14
this.FeatureBackground();
#line 28
 testRunner.When("eu acessar a nova tela de local de gravacao", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 29
 testRunner.Then("eu visualizo a nova tela de local de gravacao com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("03 - Acionar nova tela de indisponibilidade de local GROT", new string[] {
                "chrome",
                "logout"}, SourceLine=31)]
        public virtual void _03_AcionarNovaTelaDeIndisponibilidadeDeLocalGROT()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("03 - Acionar nova tela de indisponibilidade de local GROT", new string[] {
                        "chrome",
                        "logout"});
#line 32
this.ScenarioSetup(scenarioInfo);
#line 14
this.FeatureBackground();
#line 33
 testRunner.When("eu acessar a nova tela de indisponibilidade de local", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 34
 testRunner.Then("eu visualizo a nova tela de indisponibilidade de local com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04 - Acionar nova tela de sequencia cenica GROT", new string[] {
                "chrome",
                "logout"}, SourceLine=36)]
        public virtual void _04_AcionarNovaTelaDeSequenciaCenicaGROT()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("04 - Acionar nova tela de sequencia cenica GROT", new string[] {
                        "chrome",
                        "logout"});
#line 37
this.ScenarioSetup(scenarioInfo);
#line 14
this.FeatureBackground();
#line 38
 testRunner.When("eu acessar a nova tela de sequencia cenica", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 39
 testRunner.Then("eu visualizo a nova tela de sequencia cenica com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("05 - Acionar nova tela de cenarios incompativeis GROT", new string[] {
                "chrome",
                "logout"}, SourceLine=41)]
        public virtual void _05_AcionarNovaTelaDeCenariosIncompativeisGROT()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("05 - Acionar nova tela de cenarios incompativeis GROT", new string[] {
                        "chrome",
                        "logout"});
#line 42
this.ScenarioSetup(scenarioInfo);
#line 14
this.FeatureBackground();
#line 43
 testRunner.When("eu acessar a nova tela de cenarios incompativeis", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 44
 testRunner.Then("eu visualizo a nova tela de cenarios incompativeis com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("06 - Acionar nova tela de grupo local de gravacao(Regiao) GROT", new string[] {
                "chrome",
                "logout"}, SourceLine=46)]
        public virtual void _06_AcionarNovaTelaDeGrupoLocalDeGravacaoRegiaoGROT()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("06 - Acionar nova tela de grupo local de gravacao(Regiao) GROT", new string[] {
                        "chrome",
                        "logout"});
#line 47
this.ScenarioSetup(scenarioInfo);
#line 14
this.FeatureBackground();
#line 48
 testRunner.When("eu acessar a nova tela de grupo local de gravacao", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 49
 testRunner.Then("eu visualizo a nova tela de grupo local de gravacao com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("07 - Acionar nova tela de parametros de producao GROT", new string[] {
                "chrome",
                "logout"}, SourceLine=51)]
        public virtual void _07_AcionarNovaTelaDeParametrosDeProducaoGROT()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("07 - Acionar nova tela de parametros de producao GROT", new string[] {
                        "chrome",
                        "logout"});
#line 52
this.ScenarioSetup(scenarioInfo);
#line 14
this.FeatureBackground();
#line 53
 testRunner.When("eu acessar a nova tela de parametros de producao", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 54
 testRunner.Then("eu visualizo a nova tela de parametros de producao com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("08 - Acionar nova tela de gestao de alertas GROT", new string[] {
                "chrome",
                "logout"}, SourceLine=56)]
        public virtual void _08_AcionarNovaTelaDeGestaoDeAlertasGROT()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("08 - Acionar nova tela de gestao de alertas GROT", new string[] {
                        "chrome",
                        "logout"});
#line 57
this.ScenarioSetup(scenarioInfo);
#line 14
this.FeatureBackground();
#line 58
 testRunner.When("eu acessar a nova tela de gestao de alertas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 59
 testRunner.Then("eu visualizo a nova tela de gestao de alertas com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
