// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Tests.SGP.Features.GROT._01_Bloco01._01_10_Personagem
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("01.10 - Personagem", new string[] {
            "kill_Driver"}, Description="Narrativa:\r\n       Eu como administrador do sistema\r\n       Quero gerenciar os pe" +
        "rsonagens \r\n       Para ter controle das cenas que serão roteirizadas\r\n\r\nFora do" +
        " escopo:\r\n       Testes negativos", SourceFile="Features\\GROT\\01 - Bloco 01\\01.10 - Personagem\\01.10 - Personagem.feature", SourceLine=7)]
    public partial class _01_10_PersonagemFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "01.10 - Personagem.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "01.10 - Personagem", "Narrativa:\r\n       Eu como administrador do sistema\r\n       Quero gerenciar os pe" +
                    "rsonagens \r\n       Para ter controle das cenas que serão roteirizadas\r\n\r\nFora do" +
                    " escopo:\r\n       Testes negativos", ProgrammingLanguage.CSharp, new string[] {
                        "kill_Driver"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 18
#line 19
 testRunner.Given("que eu navegue para a Tela de Login do SGP", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 20
 testRunner.And("efetuar o login no sistema do SGP", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 21
 testRunner.And("que eu navegue para a Tela Home com a programacao selecionada", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("01.10.01 - Validar gravação dos dados do Tempo de preparação de Figurino/caracter" +
            "ização", new string[] {
                "chrome",
                "excluir_NovoPersonagem",
                "logout"}, SourceLine=23)]
        public virtual void _01_10_01_ValidarGravacaoDosDadosDoTempoDePreparacaoDeFigurinoCaracterizacao()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("01.10.01 - Validar gravação dos dados do Tempo de preparação de Figurino/caracter" +
                    "ização", new string[] {
                        "chrome",
                        "excluir_NovoPersonagem",
                        "logout"});
#line 24
this.ScenarioSetup(scenarioInfo);
#line 18
this.FeatureBackground();
#line 25
 testRunner.Given("que esteja na tela de Personagem", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 26
 testRunner.When("cadastrar um novo personagem", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 27
 testRunner.Then("visualizo o personagem criado com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("01.10.02 - Validar alteração de personagem sem roteiros não gravados", new string[] {
                "chrome",
                "excluir_NovoPersonagem",
                "logout"}, SourceLine=29)]
        public virtual void _01_10_02_ValidarAlteracaoDePersonagemSemRoteirosNaoGravados()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("01.10.02 - Validar alteração de personagem sem roteiros não gravados", new string[] {
                        "chrome",
                        "excluir_NovoPersonagem",
                        "logout"});
#line 30
this.ScenarioSetup(scenarioInfo);
#line 18
this.FeatureBackground();
#line 31
    testRunner.Given("que esteja na tela de Personagem", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 32
       testRunner.When("eu seleciono um Personagem para edicao", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 33
       testRunner.Then("visualizo Personagem alterado com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("01.10.03 - Tela Personagens para usuário com perfil do GROT", new string[] {
                "chrome",
                "logout"}, SourceLine=35)]
        public virtual void _01_10_03_TelaPersonagensParaUsuarioComPerfilDoGROT()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("01.10.03 - Tela Personagens para usuário com perfil do GROT", new string[] {
                        "chrome",
                        "logout"});
#line 36
this.ScenarioSetup(scenarioInfo);
#line 18
this.FeatureBackground();
#line 37
    testRunner.Given("que esteja na tela de Personagem", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 38
       testRunner.When("valido novos campos criados em Novo Personagem", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 39
       testRunner.Then("visualizo os novos campos com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("01.10.04  - Alteração de valores na tela de parâmetros", new string[] {
                "chrome",
                "alterar_ParametroProducaoPersonagem",
                "logout"}, SourceLine=41)]
        public virtual void _01_10_04_AlteracaoDeValoresNaTelaDeParametros()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("01.10.04  - Alteração de valores na tela de parâmetros", new string[] {
                        "chrome",
                        "alterar_ParametroProducaoPersonagem",
                        "logout"});
#line 42
this.ScenarioSetup(scenarioInfo);
#line 18
this.FeatureBackground();
#line 43
    testRunner.Given("que esteja na tela Parametros", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 44
       testRunner.When("eu altero os valores dos novos campos criados", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 45
       testRunner.Then("visualizo os valores alterados com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("01.10.05 - Validar LOG - Novo Personagem - Parâmetros alterados", new string[] {
                "chrome",
                "excluir_NovoPersonagem",
                "logout"}, SourceLine=47)]
        public virtual void _01_10_05_ValidarLOG_NovoPersonagem_ParametrosAlterados()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("01.10.05 - Validar LOG - Novo Personagem - Parâmetros alterados", new string[] {
                        "chrome",
                        "excluir_NovoPersonagem",
                        "logout"});
#line 48
this.ScenarioSetup(scenarioInfo);
#line 18
this.FeatureBackground();
#line 49
    testRunner.Given("que esteja na tela de Personagem", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 50
    testRunner.When("cadastrar um novo personagem alterando os valores padroes de paramentro", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 51
       testRunner.Then("visualizo o log do processo executado com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("01.10.06 - Validar LOG - Novo Personagem - parametros default do SGP", new string[] {
                "chrome",
                "excluir_NovoPersonagem",
                "logout"}, SourceLine=53)]
        public virtual void _01_10_06_ValidarLOG_NovoPersonagem_ParametrosDefaultDoSGP()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("01.10.06 - Validar LOG - Novo Personagem - parametros default do SGP", new string[] {
                        "chrome",
                        "excluir_NovoPersonagem",
                        "logout"});
#line 54
this.ScenarioSetup(scenarioInfo);
#line 18
this.FeatureBackground();
#line 55
    testRunner.Given("que esteja na tela de Personagem", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 56
       testRunner.When("cadastrar um novo personagem sem alterar os valores padroes de paramentro", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 57
       testRunner.Then("visualizo o log do processo executado com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("01.10.07 - Validar LOG - Alteração de informações do ator", new string[] {
                "chrome",
                "excluir_NovoPersonagem",
                "logout"}, SourceLine=59)]
        public virtual void _01_10_07_ValidarLOG_AlteracaoDeInformacoesDoAtor()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("01.10.07 - Validar LOG - Alteração de informações do ator", new string[] {
                        "chrome",
                        "excluir_NovoPersonagem",
                        "logout"});
#line 60
this.ScenarioSetup(scenarioInfo);
#line 18
this.FeatureBackground();
#line 61
  testRunner.Given("que esteja na tela de Personagem", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 62
  testRunner.When("cadastrar um novo personagem", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 63
  testRunner.And("alterar as informacoes do ator", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 64
  testRunner.Then("visualizo o log da alteracao feita no personagem", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("01.10.11 - Validar LOG - Limpar informações cadastradas nos novos campos", new string[] {
                "chrome",
                "excluir_NovoPersonagem",
                "logout"}, SourceLine=66)]
        public virtual void _01_10_11_ValidarLOG_LimparInformacoesCadastradasNosNovosCampos()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("01.10.11 - Validar LOG - Limpar informações cadastradas nos novos campos", new string[] {
                        "chrome",
                        "excluir_NovoPersonagem",
                        "logout"});
#line 67
this.ScenarioSetup(scenarioInfo);
#line 18
this.FeatureBackground();
#line 68
  testRunner.Given("que esteja na tela de Personagem", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 69
  testRunner.When("cadastrar um novo personagem", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 70
  testRunner.And("apagar as informacoes cadastradas nos novos campos", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 71
  testRunner.Then("visualizo o log da alteracao feita no personagem", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("02.03.01 - Alteração do Cadastro de personagem - Validar Número máximo de dias de" +
            " gravação por semana", new string[] {
                "chrome",
                "excluir_NovoPersonagem",
                "logout"}, SourceLine=73)]
        public virtual void _02_03_01_AlteracaoDoCadastroDePersonagem_ValidarNumeroMaximoDeDiasDeGravacaoPorSemana()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("02.03.01 - Alteração do Cadastro de personagem - Validar Número máximo de dias de" +
                    " gravação por semana", new string[] {
                        "chrome",
                        "excluir_NovoPersonagem",
                        "logout"});
#line 74
this.ScenarioSetup(scenarioInfo);
#line 18
this.FeatureBackground();
#line 75
    testRunner.Given("que esteja na tela de Personagem", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 76
       testRunner.When("eu seleciono um Personagem para edicao", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 77
       testRunner.Then("visualizo Personagem alterado com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
